version: 2
jobs:
  checkout_and_install:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/protocol
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}-
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: npm install --quiet
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: protocol-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/protocol
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/protocol
    steps:
      - restore_cache:
          key: protocol-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Compile contracts
          command: npm run compile -- --all
      - save_cache:
          key: protocol-completed-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/protocol
  lint:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/protocol
    steps:
      - restore_cache:
          key: protocol-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: npm run lint && npm run dydxlint && npm run solint
  test:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/protocol
    steps:
      - restore_cache:
          key: protocol-completed-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: npm test
  coverage:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/protocol
    steps:
      - restore_cache:
          key: protocol-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Coverage
          command: npm run coverage && cat coverage/lcov.info | node_modules/.bin/coveralls
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_and_install
      - build:
          requires:
            - checkout_and_install
      - lint:
          requires:
            - checkout_and_install
      - test:
          requires:
            - build
      - coverage:
          requires:
            - checkout_and_install
