version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6.0
      - image: harshjv/testrpc
    steps:
      - checkout
      - run:
          name: Update npm
          command: npm -v
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install --quiet
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Compile contracts
          command: npm run compile
      - run:
          name: Test
          command: npm test
