version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install --quiet
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:8.6.0
    steps:
      - run:
          name: Compile contracts
          command: npm run compile -- --all
  lint:
    docker:
      - image: circleci/node:8.6.0
    steps:
      - run:
          name: Lint
          command: npm run lint && npm run solint
  test:
    docker:
      - image: circleci/node:8.6.0
    steps:
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build:
        requires:
          - install
      - lint:
        requires:
          - install
      - test:
        requires:
          - build
